" Settings
set nocompatible
set encoding=utf-8
set number
set numberwidth=3
set showtabline=2
set shiftwidth=2
set tabstop=2
set smartindent
set colorcolumn=80
set path=.,,**
set expandtab
set showcmd
set autoread
set autowrite
set title
set backspace=indent,eol,start
set ruler
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set laststatus=2
set clipboard=unnamed
set ignorecase
set smartcase
set scrolloff=3
set term=xterm-256color
set visualbell
set listchars=tab:▸\ ,eol:¬,trail:⋅,nbsp:⋅
set mouse=a
set timeoutlen=500  " Time to wait after ESC (default causes an annoying delay)

" Keymaps
"
"  * general
"
map ; :
"
"  * move lines up/down
"
nnoremap <A-Down>  :m .+1<CR>==
nnoremap <A-Up>    :m .-2<CR>==
inoremap <A-Down>  <Esc>:m .+1<CR>==gi
inoremap <A-Up>    <Esc>:m .-2<CR>==gi
vnoremap <A-Down>  :m '>+1<CR>gv=gv
vnoremap <A-Up>    :m '<-2<CR>gv=gv
"
"  * navigate tabs
"
nnoremap <A-Left>  :tabprevious<CR>
nnoremap <A-Right> :tabnext<CR>
nnoremap <A-n>     :tabnew<CR>
inoremap <A-Left>  <Esc>:tabprevious<CR>i
inoremap <A-Right> <Esc>:tabnext<CR>i
inoremap <A-n>     <Esc>:tabnew<CR>
nnoremap <F3>      :tabe<Space>
nnoremap <F4>      :tabf<Space>
inoremap <F3>      <Esc>:tabe<Space>
inoremap <F4>      <Esc>:tabf<Space>
nnoremap <F6>      :NERDTreeTabsToggle<CR>
inoremap <F6>      <Esc>:NERDTreeTabsToggle<CR>
"
"  * navigate viewports
"
nnoremap <A-S-Up>    <C-w>k
nnoremap <A-S-Down>  <C-w>j
nnoremap <A-S-Left>  <C-w>h
nnoremap <A-S-Right> <C-w>l
inoremap <A-S-Up>    <Esc><C-w>ki
inoremap <A-S-Down>  <Esc><C-w>ji
inoremap <A-S-Left>  <Esc><C-w>hi
inoremap <A-S-Right> <Esc><C-w>li
"
"  * formatting
"
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>:retab<CR>
"
"  * snippets
"
imap <C-l> <Space>=><Space>
"
"  * <leader> key mappings
"
nnoremap <Leader>gs  :Gstatus<CR>
nnoremap <Leader>gd  :Gdiff<CR>
nnoremap <Leader>h   :set hlsearch!<CR>
nnoremap <Leader>sh  :set list!<CR>
nnoremap <Leader>ss  :set syntax=
nnoremap <Leader>wh  :sp<CR>
nnoremap <Leader>wv  :vsp<CR>
"
"  * text handling
"
nnoremap Y y$
" Enter a blank line below/above cursor in Normal mode.
nmap ,o o<Esc>k
nmap ,O O<Esc>j
"
"  * tags
"
nmap <F8> :TagbarToggle<CR>

" Tagbar
let g:tagbar_type_markdown = {
  \ 'ctagstype' : 'markdown',
  \ 'kinds' : [
    \ 'h:Heading_L1',
    \ 'i:Heading_L2',
    \ 'k:Heading_L3'
  \ ]
\ }

" Powerline
let g:Powerline_theme="default"

" Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

syntax on
filetype on
filetype plugin on
filetype indent on
