set nocompatible

" configure Vundle
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#begin()

Plugin 'gmarik/vundle'
Plugin 'tpope/vim-sensible'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/syntastic'
Plugin 'bling/vim-airline'
Plugin 'Townk/vim-autoclose'
Plugin 'tpope/vim-bundler'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-eunuch'
Plugin 'ngarbezza/vim-gobstones'
Plugin 'tpope/vim-markdown'
Plugin 'tangledhelix/vim-octopress'
Plugin 'tpope/vim-repeat'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-surround'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'guns/vim-clojure-static'

call vundle#end()

" General Settings
set encoding=utf-8
set title
set number
set numberwidth=3
set showtabline=2
set colorcolumn=80
set path=.,,**

" Tabs and indentation
set expandtab
set shiftwidth=2
set softtabstop=2

set autowrite
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set clipboard=unnamed
set ignorecase
set smartcase
set scrolloff=3
set term=xterm-256color
set visualbell
set mouse=a
set timeoutlen=500  " Time to wait after ESC (default causes an annoying delay)
set backupdir=~/temp/vimbackups,.
set directory=~/temp/vimbackups,.

" Keymaps
"
"  * general
"
map ;      :
map <Down> gj
map <Up>   gk
inoremap <A-d> <Esc>ddi
"
"  * move lines up/down
"
nnoremap <A-Down>  :m .+1<CR>==
nnoremap <A-Up>    :m .-2<CR>==
inoremap <A-Down>  <Esc>:m .+1<CR>==gi
inoremap <A-Up>    <Esc>:m .-2<CR>==gi
vnoremap <A-Down>  :m '>+1<CR>gv=gv
vnoremap <A-Up>    :m '<-2<CR>gv=gv
"
"  * navigate tabs
"
nnoremap <A-Left>  :tabprevious<CR>
nnoremap <A-Right> :tabnext<CR>
nnoremap <A-n>     :tabnew<CR>
inoremap <A-Left>  <Esc>:tabprevious<CR>i
inoremap <A-Right> <Esc>:tabnext<CR>i
inoremap <A-n>     <Esc>:tabnew<CR>
nnoremap <F3>      :tabe<Space>
nnoremap <F4>      :tabf<Space>
inoremap <F3>      <Esc>:tabe<Space>
inoremap <F4>      <Esc>:tabf<Space>
"
"  * navigate viewports
"
nnoremap <A-S-Up>    <C-w>k
nnoremap <A-S-Down>  <C-w>j
nnoremap <A-S-Left>  <C-w>h
nnoremap <A-S-Right> <C-w>l
inoremap <A-S-Up>    <Esc><C-w>ki
inoremap <A-S-Down>  <Esc><C-w>ji
inoremap <A-S-Left>  <Esc><C-w>hi
inoremap <A-S-Right> <Esc><C-w>li
"
"  * formatting
"
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>:retab<CR>
"
"  * snippets
"
imap <C-l> <Space>=><Space>
"
"  * <leader> key mappings
"
nnoremap <Leader>gs  :Gstatus<CR>
nnoremap <Leader>gd  :Gdiff<CR>
nnoremap <Leader>h   :set hlsearch!<CR>
nnoremap <Leader>sh  :set list!<CR>
nnoremap <Leader>ss  :set syntax=
nnoremap <Leader>wh  :sp<CR>
nnoremap <Leader>wv  :vsp<CR>
nnoremap <Leader>tp  :set invpaste<CR>
"
"  * vim-rspec plugin mappings
"
map <Leader>sf :call RunCurrentSpecFile()<CR>
map <Leader>sc :call RunNearestSpec()<CR>
map <Leader>sl :call RunLastSpec()<CR>
map <Leader>sa :call RunAllSpecs()<CR>
"
"  * text handling
"
nnoremap Y y$
" Enter a blank line below/above cursor in Normal mode.
nmap ,o o<Esc>k
nmap ,O O<Esc>j

" GitGutter
let g:gitgutter_enabled = 0
map <Leader>gg :GitGutterToggle<CR>

" Powerline
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" Rainbow Patentheses
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0
map <Leader>rpt :RainbowParenthesesToggle<CR>

" Hiccup
au BufRead,BufNewFile *.hiccup set filetype=clojure

set wildignore+=*/tmp/*,*/target*
" CtrlP
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$',
  \ 'file': '\.so$\|\.dat$'
  \ }
let g:ctrlp_prompt_mappings = {
  \ 'AcceptSelection("e")': ['<c-t>'],
  \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
  \ }

syntax on
set background=dark
colorscheme solarized
filetype on
filetype plugin on
filetype indent on
