#!/usr/bin/env python

import os

def ask_for(message, key):
  option = raw_input('%s (Enter to skip): ' % message)
  set_option(key, option)

def set_option(key, value):
  if value: os.system('git config --global %s "%s"' % (key, value))

# Set up base template gitconfig
path = os.path.dirname(os.path.realpath(__file__))
os.system('cp %s/../configurations/gitconfig ~/.gitconfig' % path)

# Set up personal specific settings
ask_for('Name', 'user.name')
ask_for('Email', 'user.email')
ask_for('GitHub User', 'github.user')
ask_for('GitHub Token', 'github.token')

print('Git Configuration file updated successfully:')
os.system('cat ~/.gitconfig')
