alias vu='vagrant up'
alias vp='vagrant provision'
alias vs='vagrant ssh'
alias vup='vagrant up --provision'
alias vus='vagrant up && vagrant ssh'
alias vh='vagrant halt'
alias vd='vagrant destroy'
alias vr='vagrant reload'
